name: Sync keys.txt to HOI4-Anti-Cheat-Ghost-

on:
  push:
    branches:
      - main  # Запускать действие при изменении в основной ветке

jobs:
  copy-file:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Получаем токен и загружаем файл keys.txt из приватного репозитория
      - name: Download keys.txt
        run: |
          curl -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
               -L \
               -o keys.txt \
               https://raw.githubusercontent.com/Wolfram49/keys/main/keys.txt

      # Шаг 2: Клонируем публичный репозиторий
      - name: Clone HOI4-Anti-Cheat-Ghost- repo
        run: |
          git clone https://github.com/Wolfram49/HOI4-Anti-Cheat-Ghost-.git
          cd HOI4-Anti-Cheat-Ghost-

      # Шаг 3: Копируем файл keys.txt
      - name: Copy keys.txt
        run: |
          cp ../keys.txt .

      # Шаг 4: Коммитим и пушим изменения
      - name: Commit changes
        run: |
          cd HOI4-Anti-Cheat-Ghost-
          git config --global user.email "vadimbabatenko@gmail.com"
          git config --global user.name "Wolfram49"
          git add keys.txt
          git commit -m "Synced keys.txt from keys repo"
          git push https://github.com/Wolfram49/HOI4-Anti-Cheat-Ghost-.git
