name: Sync keys.txt to HOI4-Anti-Cheat-Ghost

on:
  push:
    branches:
      - main  # Запускать действие при изменениях в основной ветке

jobs:
  copy-file:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонируем репозиторий `keys`
      - name: Checkout keys repo
        uses: actions/checkout@v2
        with:
          repository: Wolfram49/keys
          token: ${{ secrets.GITHUB_TOKEN }}

      # Шаг 2: Клонируем публичный репозиторий `HOI4-Anti-Cheat-Ghost`
      - name: Clone HOI4-Anti-Cheat-Ghost repo
        run: |
          git clone https://github.com/Wolfram49/HOI4-Anti-Cheat-Ghost.git
          cd HOI4-Anti-Cheat-Ghost

      # Шаг 3: Копируем файл `keys.txt` в репозиторий `HOI4-Anti-Cheat-Ghost`
      - name: Copy keys.txt
        run: |
          cp ../keys.txt HOI4-Anti-Cheat-Ghost/  # Копируем файл

      # Шаг 4: Коммитим изменения в репозиторий `HOI4-Anti-Cheat-Ghost`
      - name: Commit changes
        run: |
          cd HOI4-Anti-Cheat-Ghost
          git config --global user.email "vadimbabatenko@gmail.com"
          git config --global user.name "Wolfram49"
          git add keys.txt
          git commit -m "Sync keys.txt from keys repo"

      # Шаг 5: Пушим изменения в репозиторий `HOI4-Anti-Cheat-Ghost`
      - name: Push changes
        run: |
          cd HOI4-Anti-Cheat-Ghost
          git push https://github.com/Wolfram49/HOI4-Anti-Cheat-Ghost.git
