name: Sync keys.txt to HOI4-Anti-Cheat-Ghost-

on:
  push:
    branches:
      - main  # Запускать действие при изменении в основной ветке

jobs:
  copy-file:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Получаем токен и загружаем содержимое файла keys.txt из приватного репозитория
      - name: Download keys.txt from private repo
        run: |
          # Удаляем предыдущий файл, если существует
          rm -f keys.txt
          
          # Загружаем файл напрямую и сохраняем его
          curl -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
               -H "Cache-Control: no-cache" \
               -L \
               -o keys.txt \
               https://raw.githubusercontent.com/Wolfram49/keys/main/keys.txt

      # Шаг 2: Проверяем наличие файла keys.txt
      - name: Check keys.txt
        run: |
          echo "Checking keys.txt:"
          ls -la
          cat keys.txt

      # Шаг 3: Клонируем публичный репозиторий
      - name: Clone HOI4-Anti-Cheat-Ghost- repo
        run: |
          git clone https://github.com/Wolfram49/HOI4-Anti-Cheat-Ghost-.git

      # Шаг 4: Проверяем содержимое директории HOI4-Anti-Cheat-Ghost-
      - name: List files in HOI4-Anti-Cheat-Ghost-
        run: |
          ls -la HOI4-Anti-Cheat-Ghost-

      # Шаг 5: Копируем файл keys.txt в директорию репозитория
      - name: Copy keys.txt to repo
        run: |
          cp keys.txt HOI4-Anti-Cheat-Ghost-/keys.txt

      # Шаг 6: Коммитим и пушим изменения
      - name: Commit and push changes
        run: |
          cd HOI4-Anti-Cheat-Ghost-
          git config --global user.email "vadimbabatenko@gmail.com"
          git config --global user.name "Wolfram49"
          git add keys.txt
          git commit -m "Synced keys.txt from keys repo"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Wolfram49/HOI4-Anti-Cheat-Ghost-.git HEAD:main
